// Code generated by vango. DO NOT EDIT.
// Source: vango_state_manifest.json
// Generator: vango gen bindings

package routes

import "github.com/vango-go/vango/pkg/runtime"

func init() {
	runtime.SetEmbeddedBindingsHash("752a5886c8279afa")
	runtime.RegisterSetupCallsites(map[string][]runtime.SetupCallsite{
		"rhone_chat/app/routes.ChatRoot": {
			{Line: 94, SetupIndex: 0},
		},
	})
	runtime.RegisterBindings(map[string]runtime.BindingInfo{
		"rhone_chat/app/routes.ChatRoot#setup0.local.action@0": {
			StableID:         "0f9b48e4",
			DebugName:        "loadChatsAction",
			CodecFingerprint: "fp:v1:17bf886d7f0a66f07e563f9aa9bbe8e237e64d2a4862643edc3aa55825205c80",
			Kind:             "action",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.action@1": {
			StableID:         "85c49bdb",
			DebugName:        "loadMessagesAction",
			CodecFingerprint: "fp:v1:2624aa9a712755261de6ba9772c299365c8eecdb8849f88df93629af990de661",
			Kind:             "action",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.action@2": {
			StableID:         "190e3746",
			DebugName:        "createChatAction",
			CodecFingerprint: "fp:v1:67d098aa4c6c18da2c5dc237a33a7f9b166cab3bd4ba0d0d795139142e0d13c9",
			Kind:             "action",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.action@3": {
			StableID:         "c15ee6a1",
			DebugName:        "renameChatAction",
			CodecFingerprint: "fp:v1:a4f82da79700e0e70028d59cc572aa113c030924f0c44a67aedbb528b0fa58a4",
			Kind:             "action",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.action@4": {
			StableID:         "b9f8ba71",
			DebugName:        "deleteChatAction",
			CodecFingerprint: "fp:v1:fa30110db74287f322220d65817f476b95b391fe4d4e162792d46f662065721a",
			Kind:             "action",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.effect@0": {
			StableID:         "9bb835d6",
			DebugName:        "deleteChatAction",
			CodecFingerprint: "fp:v1:586aedd755559370a572572b88b49b32264f73f15956f20e19aeca1633599b9d",
			Kind:             "effect",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.effect@1": {
			StableID:         "deaee0ba",
			DebugName:        "deleteChatAction",
			CodecFingerprint: "fp:v1:586aedd755559370a572572b88b49b32264f73f15956f20e19aeca1633599b9d",
			Kind:             "effect",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.onmount@0": {
			StableID:         "17b0ff56",
			DebugName:        "deleteChatAction",
			CodecFingerprint: "fp:v1:586aedd755559370a572572b88b49b32264f73f15956f20e19aeca1633599b9d",
			Kind:             "onmount",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@0": {
			StableID:         "06c6ecdc",
			DebugName:        "chats",
			CodecFingerprint: "fp:v1:f9a49008bb23464df3798ce30b8cd6374cdfe27dc441360e865187b8f2e75a46",
			Kind:             "signal",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@1": {
			StableID:         "a9c3f9cf",
			DebugName:        "messages",
			CodecFingerprint: "fp:v1:a0771a92ef22a342514887e8e95bc006518ef6eb7fbe146e8930b4a9c50db318",
			Kind:             "signal",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@10": {
			StableID:         "e88168fd",
			DebugName:        "editingChatID",
			CodecFingerprint: "fp:v1:25adb695cf48816c4c034c305c055a4c4956ee6270648b88ae6d408d845e6c2f",
			Kind:             "signal",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@11": {
			StableID:         "9bb51fb8",
			DebugName:        "renameTitle",
			CodecFingerprint: "fp:v1:25adb695cf48816c4c034c305c055a4c4956ee6270648b88ae6d408d845e6c2f",
			Kind:             "signal",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@12": {
			StableID:         "ccac82cf",
			DebugName:        "runTrigger",
			CodecFingerprint: "fp:v1:41f520f90e9cc9458b0ee392ee4b7e474da42b9cd0c8725da11e93d92bab00c6",
			Kind:             "signal",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@13": {
			StableID:         "ada2fa79",
			DebugName:        "pendingRun",
			CodecFingerprint: "fp:v1:f741c9f871696f686e18c353b25327c15630e1fbb0f4bb4e973ef7cfc9fb9292",
			Kind:             "signal",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@2": {
			StableID:         "83feeebd",
			DebugName:        "activeChatID",
			CodecFingerprint: "fp:v1:25adb695cf48816c4c034c305c055a4c4956ee6270648b88ae6d408d845e6c2f",
			Kind:             "signal",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@3": {
			StableID:         "335a7965",
			DebugName:        "inputText",
			CodecFingerprint: "fp:v1:25adb695cf48816c4c034c305c055a4c4956ee6270648b88ae6d408d845e6c2f",
			Kind:             "signal",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@4": {
			StableID:         "8617a5cd",
			DebugName:        "selectedModel",
			CodecFingerprint: "fp:v1:25adb695cf48816c4c034c305c055a4c4956ee6270648b88ae6d408d845e6c2f",
			Kind:             "signal",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@5": {
			StableID:         "4e2c0d96",
			DebugName:        "errorText",
			CodecFingerprint: "fp:v1:25adb695cf48816c4c034c305c055a4c4956ee6270648b88ae6d408d845e6c2f",
			Kind:             "signal",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@6": {
			StableID:         "04e9871e",
			DebugName:        "isThinking",
			CodecFingerprint: "fp:v1:bd0f738432faad57453a335bb6ec3cef8e52a0695dfa14c62d0cf900dcbdd26c",
			Kind:             "signal",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@7": {
			StableID:         "49be5647",
			DebugName:        "activeRunID",
			CodecFingerprint: "fp:v1:25adb695cf48816c4c034c305c055a4c4956ee6270648b88ae6d408d845e6c2f",
			Kind:             "signal",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@8": {
			StableID:         "ccdd2113",
			DebugName:        "activeAssistantID",
			CodecFingerprint: "fp:v1:25adb695cf48816c4c034c305c055a4c4956ee6270648b88ae6d408d845e6c2f",
			Kind:             "signal",
			Class:            "local",
		},
		"rhone_chat/app/routes.ChatRoot#setup0.local.signal@9": {
			StableID:         "8e5b3826",
			DebugName:        "themeMode",
			CodecFingerprint: "fp:v1:25adb695cf48816c4c034c305c055a4c4956ee6270648b88ae6d408d845e6c2f",
			Kind:             "signal",
			Class:            "local",
		},
	})
}
